log_format   custom '$remote_addr - $remote_user [$time_local]  $status '
'"$request" $body_bytes_sent "$http_referer" '
'"$http_user_agent" "$http_x_forwarded_for"'
'uri: "$uri", is_args: "$is_args", args: "$args"';

server {
  listen       80;
  access_log /var/log/nginx/access.log custom;
  error_log /var/log/nginx/error.log;

  location / {
      root   /usr/share/nginx/html/build;
      try_files $uri /index.html;
  }
}
